subject = "Название предмета"
description = "Материалы для подготовки к зачёту/экзамену"
term = 4                                                   # номер семестра
authors = ["Данила Григорьев"]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
  "Интерактивное приложение. Интерактивная машинная графика.",
  "Событийно-ориентированное программирование. Основные варианты событий и их обработчиков при построении интерактивного графического приложения.",
  "Декартова система координат (ДСК). Модельная (локальная, объектная) система координат. Система координат экрана.",
  "Вывод преобразования кадрирования без сохранения пропорций изображения.",
  "Сохранение пропорций изображения при преобразовании кадрирования.",
  "Однородные координаты. Переход от евклидовых к однородным координатам и обратно.",
  "2D-преобразования — масштабирование и поворот относительно начала координат. Получение матриц преобразований. Обратные преобразования.",
  "2D-преобразование — перенос. Получение матрицы преобразования. Обратное преобразования.",
  "Совмещение 2D-преобразований преобразований. Получение матрицы совмещенного преобразования. Обратное преобразование для совмещенного преобразования.",
  "Алгоритм Коэна—Сазерленда отсечения невидимых линий.",
  "Алгоритм построения простого графика функции: двумерного, трехмерного.",
  "Мировая система координат. Модельное преобразование. Вывод матрицы варианта модельного преобразования.",
  "3D-преобразования — масштабирование и вращение относительно осей координат. Получение матриц преобразований. Обратные преобразования.",
  "3D-преобразование — перенос. Получение матрицы преобразования. Обратное преобразования.",
  "Скалярное произведение. Геометрический смысл скалярного произведения. Векторное произведение. Вывод матрицы векторного произведения.",
  "Двойственность преобразований (каждого из преобразований). Переход от одного базиса ДСК к другому.",
  "Трехмерное вращение относительно оси, проходящей через начало координат. Вывод формулы Родригеса.",
  "Матрица преобразования нормалей.",
  "Система координат наблюдателя (СКН). Переход от мировой системы координат к СКН. Вывод матрицы преобразования LookAt.",
  "Организация интерактивного движения в пространстве наблюдателя.",
  "Система координат пространства отсечения. Вывод матрицы преобразования Ortho.",
  "Система координат пространства отсечения. Вывод матрицы преобразования Frustum.",
  "Система координат пространства отсечения. Вывод матрицы преобразования Perspective.",
  "Растеризация отрезка. Алгоритм Брезенхема.",
  "Растеризация многоугольника. Алгоритм построчного заполнения.",
  "Алгоритм использующий Z-буфер.",
  "Элементы OpenGL: Графический конвейер.",
  "Вершинные данные. Вершинный массив. Вершинный буфер.",
  "Шейдерная программа (варианты шейдеров). Порядок работы. Uniform-переменные.",
  "Типы источников света: точечный, линейный, плоскостной, бесконечно удаленный. Влияние типа источника света на освещенность точки.",
  "Модель освещения Фонга.",
  "Модель освещения Блинна—Фонга.",
  "Модели затенения Гуро и Фонга.",
  "Порядок реализации модели Гуро с помощью шейдеров в OpenGL.",
  "Порядок реализации модели Фонга с помощью шейдеров в OpenGL.",
]
